import 'package:flutter/material.dart';

class GameModel {
  final String id;
  final String titleAr;
  final String titleEn;
  final String subtitle;
  final IconData icon;
  final Color primaryColor;
  final int onlinePlayers;
  final int maxPlayers;
  final String badgeTag;
  final String category;
  final bool isPopular;
  final bool isNew;
  final List<Color> cardGradientColors;
  final String cardEmoji;
  final String cardImagePath;

  GameModel({
    required this.id,
    required this.titleAr,
    required this.titleEn,
    required this.subtitle,
    required this.icon,
    required this.primaryColor,
    required this.onlinePlayers,
    required this.maxPlayers,
    required this.badgeTag,
    required this.category,
    required this.cardGradientColors,
    required this.cardEmoji,
    required this.cardImagePath,
    this.isPopular = false,
    this.isNew = false,
  });

  static List<GameModel> get gamesList => [
    // ════ ROW 1 (5 GAMES) ════
    GameModel(
      id: 'poker',
      titleAr: 'بوكر',
      titleEn: 'POKER',
      subtitle: 'لعبة الورق والرهانات الكلاسيكية',
      icon: Icons.style,
      primaryColor: const Color(0xFFFFD700),
      cardGradientColors: const [Color(0xFF3A0D0D), Color(0xFF6B1515), Color(0xFF1E0505)],
      cardEmoji: '🎴',
      cardImagePath: 'assets/images/baloot.png',
      onlinePlayers: 4250,
      maxPlayers: 4,
      badgeTag: 'شبيكة 🎴',
      category: 'ورق',
      isPopular: true,
    ),
    GameModel(
      id: 'chess',
      titleAr: 'الشطرنج',
      titleEn: 'CHESS',
      subtitle: 'صراع عقول السلاطين والفرسان',
      icon: Icons.shield,
      primaryColor: const Color(0xFFE0E0E0),
      cardGradientColors: const [Color(0xFF2E1A0E), Color(0xFF532E16), Color(0xFF1A0E08)],
      cardEmoji: '♟️',
      cardImagePath: 'assets/images/chess.png',
      onlinePlayers: 1890,
      maxPlayers: 2,
      badgeTag: 'ذكاء ♟️',
      category: 'استراتيجية',
    ),
    GameModel(
      id: 'backgammon',
      titleAr: 'طاولة',
      titleEn: 'BACKGAMMON',
      subtitle: 'طاولة الزهر المصرية والخليجية الاصيلة',
      icon: Icons.casino,
      primaryColor: const Color(0xFFFF9100),
      cardGradientColors: const [Color(0xFF3D1805), Color(0xFF6E2D09), Color(0xFF1A0A02)],
      cardEmoji: '🎲',
      cardImagePath: 'assets/images/jackaroo.png',
      onlinePlayers: 3400,
      maxPlayers: 2,
      badgeTag: 'زهر 🎲',
      category: 'طاولة',
      isPopular: true,
    ),
    GameModel(
      id: 'jackaroo',
      titleAr: 'جاكارو',
      titleEn: 'JACKAROO',
      subtitle: 'لعبة الألواح الشهيرة بالأحجار والأوراق',
      icon: Icons.auto_awesome_motion,
      primaryColor: const Color(0xFF00E676),
      cardGradientColors: const [Color(0xFF052B11), Color(0xFF0C5424), Color(0xFF021408)],
      cardEmoji: '🃏',
      cardImagePath: 'assets/images/jackaroo.png',
      onlinePlayers: 4100,
      maxPlayers: 4,
      badgeTag: 'تحدي 👥',
      category: 'ألواح',
      isNew: true,
    ),
    GameModel(
      id: 'domino',
      titleAr: 'الدومينو',
      titleEn: 'DOMINO',
      subtitle: 'الدومينو المصرية والخليجية التنافسية',
      icon: Icons.grid_view,
      primaryColor: const Color(0xFFFFB300),
      cardGradientColors: const [Color(0xFF2E2205), Color(0xFF59430A), Color(0xFF171102)],
      cardEmoji: '🀄',
      cardImagePath: 'assets/images/dominoes.png',
      onlinePlayers: 3200,
      maxPlayers: 2,
      badgeTag: 'كلاسيكي 🀄',
      category: 'طاولة',
      isPopular: true,
    ),

    // ════ ROW 2 (5 GAMES) ════
    GameModel(
      id: 'snakes',
      titleAr: 'السلم والثعبان',
      titleEn: 'SNAKES & LADDERS',
      subtitle: 'مغامرة الصعود والهبوط لجميع الأعمار',
      icon: Icons.trending_up,
      primaryColor: const Color(0xFF4CAF50),
      cardGradientColors: const [Color(0xFF142B05), Color(0xFF27540C), Color(0xFF0A1402)],
      cardEmoji: '🐍',
      cardImagePath: 'assets/images/carrom.png',
      onlinePlayers: 2600,
      maxPlayers: 4,
      badgeTag: 'عائلي 🐍',
      category: 'عائلي',
    ),
    GameModel(
      id: 'parchisi',
      titleAr: 'بارشيسي',
      titleEn: 'PARCHISI',
      subtitle: 'سباق الزهر والقطع التكتيكي السريع',
      icon: Icons.stars,
      primaryColor: const Color(0xFFFF3D00),
      cardGradientColors: const [Color(0xFF380E05), Color(0xFF6B1F0B), Color(0xFF1C0602)],
      cardEmoji: '🎲',
      cardImagePath: 'assets/images/jackaroo.png',
      onlinePlayers: 2950,
      maxPlayers: 4,
      badgeTag: 'سريع 🎲',
      category: 'ألواح',
      isNew: true,
    ),
    GameModel(
      id: 'ludo',
      titleAr: 'لودو',
      titleEn: 'LUODO',
      subtitle: 'سباق الخيول والأقشطة وحماس الأصدقاء',
      icon: Icons.sports_esports,
      primaryColor: const Color(0xFFE91E63),
      cardGradientColors: const [Color(0xFF360517), Color(0xFF660E2F), Color(0xFF1B020B)],
      cardEmoji: '🎯',
      cardImagePath: 'assets/images/carrom.png',
      onlinePlayers: 4800,
      maxPlayers: 4,
      badgeTag: 'حماس 🎯',
      category: 'عائلي',
      isPopular: true,
    ),
    GameModel(
      id: 'ball8',
      titleAr: 'البلياردو',
      titleEn: '8BALL',
      subtitle: 'تحدي كرات البلياردو والسرعة الدقيقة',
      icon: Icons.circle,
      primaryColor: const Color(0xFF00F2FE),
      cardGradientColors: const [Color(0xFF05232B), Color(0xFF0C4654), Color(0xFF021117)],
      cardEmoji: '🎱',
      cardImagePath: 'assets/images/carrom.png',
      onlinePlayers: 3600,
      maxPlayers: 2,
      badgeTag: 'تصويب 🎱',
      category: 'رياضة',
    ),
    GameModel(
      id: 'tarneeb',
      titleAr: 'الطرنيب',
      titleEn: 'TARNEEB',
      subtitle: 'تحدي الشام والتخطيط الاستراتيجي للورق',
      icon: Icons.subtitles,
      primaryColor: const Color(0xFFFF2A6D),
      cardGradientColors: const [Color(0xFF2E051D), Color(0xFF590C3B), Color(0xFF17020E)],
      cardEmoji: '🎴',
      cardImagePath: 'assets/images/tarneeb.png',
      onlinePlayers: 2900,
      maxPlayers: 4,
      badgeTag: 'تحدي 🎴',
      category: 'ورق',
    ),
  ];
}
